---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemma4-e2b
  name: gemma4-e2b
  namespace: llm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma4-e2b
  template:
    metadata:
      labels:
        app: gemma4-e2b
    spec:
      runtimeClassName: nvidia
      containers:
      - image: ghcr.io/ggml-org/llama.cpp:server-cuda13
        name: main
        ports:
          - containerPort: 8080
        env:
        - name: NVIDIA_DISABLE_REQUIRE
          value: "true"
        - name: LLAMA_ARG_HF_REPO
          value: google/gemma-4-E2B-it-qat-q4_0-gguf
        - name: LLAMA_ARG_MMPROJ
          value: /root/.cache/huggingface/hub/models--google--gemma-4-E2B-it-qat-q4_0-gguf/snapshots/675cff42a74c774d6cb76f76d8eacb49b48c9b93/gemma-4-E2B-it-mmproj.gguf
        - name: LLAMA_ARG_REASONING
          value: "off"
        - name: LLAMA_ARG_CACHE_PROMPT
          value: "false"
        - name: LLAMA_ARG_CTX_SIZE
          value: "4096"
        - name: LLAMA_ARG_PORT
          value: "8080"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        resources:
          requests:
            cpu: "2"
            memory: 2Gi
          limits:
            cpu: "6"
            memory: 8Gi
        volumeMounts:
        - name: cache-volume
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: cache-volume
        hostPath:
          path: /home/yasuaki/.cache/huggingface/
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
