[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pyaudio>=0.2.14",
    "scipy>=1.18.1",
    "silero-vad>=6.2.1",
    "torch>=2.14.0",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "test",
    "app",
]
