---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audio-app
  name: audio-app
  namespace: llm-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audio-app
  template:
    metadata:
      labels:
        app: audio-app
    spec:
      #runtimeClassName: nvidia
      containers:
      - image: harbor.cluster.orenet.net/llm-system/audio-app:latest
        name: main
        env:
        - name: OPENAI_API_KEY
          value: dummy
        - name: OPENAI_BASE_URL
          value: http://gemma4-e2b:8080/v1
        - name: OPENAI_MODEL
          value: google/gemma-4-E2B-it-qat-q4_0-gguf
        resources:
          limits:
            devic.es/audio: 1
